openapi: 3.0.0
tags:
  - name: Admin Auth
    description: 관리자 인증
  - name: Dashboard
    description: 통계 차트
  - name: System Variable
    description: 시스템 환경 변수값 관리
  - name: Charm Plan
    description: 매력 포인트 플랜 관리
  - name: Help Desk
    description: 헬프 데스크 관리
  - name: Q&A
    description: 문의글&답변 관리
  - name: Profile Extra Item
    description: 프로필 추가 항목
  - name: User Block
    description: 신고/차단
  - name: User Interest
    description: 관심사/싫어요
  - name: User Photo
    description: 유저 사진
  - name: User Profile
    description: 유저 프로필
info:
  description: Madam 앱 관리자용 클라이언트에 필요한 API 스펙 1차 정의.
  version: 1.0.0
  title: Madam Admin Client Requests API
  license:
    name: UNLICENSED
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Admin:
      type: object
      properties:
        email:
          type: string
          format: email
          description: 사용자 이메일
          example: madam@example.com
        key:
          type: string
          description: 암호화 된 Google Firebase Auth Credential ID
          example: key
        name:
          type: string
          description: Google Firebase 인증에서 가져온 표시되는 사용자 명칭
          example: Madam
    SystemVariable:
      type: object
      properties:
        type:
          type: string
          description: '구분값 (예: DB / POINT_CALC / ...)'
          example: POINT_CALC
        key:
          type: string
          description: 환경변수 명칭(내부 키)
          example: CALC_1
        value:
          type: string
          description: 값
          example: '10'
        use:
          type: boolean
          description: 사용여부
          example: true
        modifierName:
          type: string
          format: email
          description: 최종 수정 관리자 명
          example: Julius
        createdAt:
          type: string
          format: date-time
          description: 생성일시
          example: '2021-08-09T21:59:00.000Z'
        modifiedAt:
          type: string
          format: date-time
          description: 생성일시
          example: '2021-08-09T21:59:00.000Z'
    CharmPlan:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 고유 키
          example: 1
        name:
          type: string
          description: 플랜 명칭
          example: Charm 10
        description:
          type: string
          description: 플랜 설명
          example: 매력 포인트 +10
        dollar:
          type: integer
          format: int32
          description: 플랜 가격(USD)
          example: 10.00
        charm:
          type: integer
          format: int32
          description: 포인트
          example: 10
        order:
          type: integer
          format: int32
          description: 표출 순서
          example: 1
        purchasedCount:
          type: integer
          format: int32
          description: 구매 횟수
          example: 100000
        createdAt:
          type: string
          format: date-time
          description: 생성일시
          example: '2021-08-09T21:59:00.000Z'
        modifiedAt:
          type: string
          format: date-time
          description: 생성일시
          example: '2021-08-09T21:59:00.000Z'
        modifierName:
          type: string
          description: 최종 수정 관리자 명
          example: Julius
    Guide:
      type: object
      properties:
        key:
          type: string
          description: 고유 키
          enum:
            - APP_BASE_KR
            - APP_BASE_EN
            - ACCOUNT_KR
            - ACCOUNT_EN
            - COUPLING_KR
            - COUPLING_EN
            - MEETING_KR
            - MEETING_EN
            - BEST_MADAM_KR
            - BEST_MADAM_EN
            - TEAM_KR
            - TEAM_EN
          example: APP_BASE_KR
        icon:
          type: string
          description: 아이콘 경로/명
          example: xi-close
        content:
          type: string
          description: 글 내용
          example: |
            # 헬프데스크
              1. 이것은 헬프데스크입니다
        display:
          type: boolean
          description: 글 표시여부
          example: true
        modifiedAt:
          type: string
          format: date-time
          description: 생성일시
          example: '2021-08-09T21:59:00.000Z'
        modifierName:
          type: string
          description: 최종 수정 관리자 명
    Inquiry:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 문의글 고유 키
          example: 1
        nickname:
          type: string
          description: 문의글 작성자 닉네임
          example: Madam
        type:
          type: string
          description: 문의 유형
          enum:
            - INQUIRY
            - REQUEST
            - ETC
          example: INQUIRY
        title:
          type: string
          description: 문의글 제목
          example: 문의글
        answered:
          type: boolean
          description: 답변 여부
          example: true
        answeredManagerName:
          type: string
          description: 답변 관리자 명
          example: Julius
        createdAt:
          type: string
          format: date-time
          description: 문의글 최종 수정일시
          example: '2021-08-09T21:59:00.000Z'
        answeredAt:
          type: string
          format: date-time
          description: 답변 최종 수정일시
          example: '2021-08-09T21:59:00.000Z'
    InquiryDetail:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 문의글 고유 키
          example: 1
        nickname:
          type: string
          description: 문의글 작성자 닉네임
          example: Madam
        type:
          type: string
          description: 문의 유형
          enum:
            - INQUIRY
            - REQUEST
            - ETC
          example: INQUIRY
        title:
          type: string
          description: 문의글 제목
          example: 문의글
        content:
          type: string
          description: 문의글 내용
          example: |
            # Madam앱이 좋은이유
              - 최고니깐
        answered:
          type: boolean
          description: 답변 여부
          example: true
        answeredManagerName:
          type: string
          description: 답변 관리자 명
          example: Julius
        answer:
          type: string
          example: |
            # 감사합니다!
        createdAt:
          type: string
          format: date-time
          description: 문의글 최종 수정일시
          example: '2021-08-09T21:59:00.000Z'
        answeredAt:
          type: string
          format: date-time
          description: 답변 최종 수정일시
          example: '2021-08-09T21:59:00.000Z'
    InquiryAnswer:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 문의글 고유 키
          example: 1
        content:
          type: string
          description: 답변 내용
          example: |
            # 감사합니다!
        modifierEmail:
          type: string
          format: email
          description: 답변 관리자 이메일
          example: madam@example.com
    ProfileExtraItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 프로필 추가 항목 고유 키
          example: 1
        titleKr:
          type: string
          description: 프로필 추가 항목 한글 명칭
          example: MBTI
        titleEn:
          type: string
          description: 프로필 추가 항목 영문 명칭
          example: MBTI
        type:
          type: string
          description: 타입
          enum:
            - TEXT
            - NUMBER
            - TEXT_AREA
            - SELECT
            - MULTI_SELECT
            - RADIO
          example: SELECT
        inputLength:
          type: integer
          format: int32
          description: 타입이 TEXT / TEXT_AREA일 시, 최대 입력 가능 글자수. MULT_SELECT일 시, 최대 선택 가능 항목 수
          example: null
        modifiedAt:
          type: string
          format: date-time
          description: 최종 수정일시
          example: '2021-08-09T21:59:00.000Z'
        modifierName:
          type: string
          description: 최종 수정 관리자 명
          example: Julius
    ProfileSelectItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 프로필 추가 항목 고유 키
          example: 1
        key:
          type: string
          description: 선택요소 고유 키
          example: ISTJ
        value:
          type: string
          description: 선택요소 값
          example: ISTJ
        use:
          type: boolean
          description: 사용여부
          example: true
        modifiedAt:
          type: string
          format: date-time
          description: 최종 수정일시
          example: '2021-08-09T21:59:00.000Z'
        modifierName:
          type: string
          description: 최종 수정 관리자 명
          example: Julius
paths:
  /login:
    post:
      tags:
        - Admin Auth
      summary: 관리자 로그인
      description: Google Firebase 인증 이메일과 암호화된 Auth Credential ID을 DB에서 인증하고 로그인 처리한다
      requestBody:
        description: Google Firebase 인증 이메일 / 암호화된 Auth Credential ID
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: madam@example.com
                key:
                  type: string
                  example: key
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: Admin
                example:
                  email: madam@example.com
                  key: key
                  name: Madam
        204:
          description: No Content
        400:
          description: Invalid Request Params
        403:
          description: No Authority
        500:
          description: Server Error
  /logout:
    post:
      security:
        - bearerAuth: []
      tags:
        - Admin Auth
      summary: 관리자 로그아웃
      description: 로그인 시 발행된 토큰 만료처리
      requestBody:
        description: 로그인 시 발행된 토큰
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: token
      responses:
        200:
          description: Success
        400:
          description: Invalid Request Params
        403:
          description: No Authority
        500:
          description: Server Error
  /name:
    put:
      security:
        - bearerAuth: []
      tags:
        - Admin Auth
      summary: 관리자 명 변경
      description: 관리자 사용자명 변경
      requestBody:
        description: Google Firebase 인증 이메일 / 암호화된 Auth Credential ID
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: madam@example.com
                key:
                  type: string
                  example: key
                name:
                  type: string
                  example: MadamNew
      responses:
        200:
          description: Success
        400:
          description: Invalid Request Params
        403:
          description: No Authority
        500:
          description: Server Error
  /system-variables:
    get:
      security:
        - bearerAuth: []
      tags:
        - System Variable
      summary: 시스템 환경 변수 목록 조회
      description: 시스템 환경 변수 목록 조회
      parameters:
        - in: query
          name: pageSize
          description: 조회 항목 개수
          required: true
          schema:
            type: integer
            format: int32
            example: 10
        - in: query
          name: pageNumber
          description: 조회 페이지 번호
          required: true
          schema:
            type: integer
            format: int32
            example: 1
        - in: query
          name: key
          description: 변수 명칭 (LIKE 검색)
          required: false
          schema:
            type: string
            example: CALC_1
        - in: query
          name: type
          description: 변수 구분값
          required: false
          schema:
            type: string
            example: POINT_CALC
        - in: query
          name: use
          description: 사용여부
          required: false
          schema:
            type: boolean
            example: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  format: SystemVariable
                example:
                  - type: POINT_CALC
                    key: CALC_1
                    value: '10'
                    use: true
                    modifierName: Julius
                    createdAt: '2021-08-09T21:59:00.000Z'
                    modifiedAt: '2021-08-09T21:59:00.000Z'
        204:
          description: No Content
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
  /system-variables/:type/:key:
    post:
      security:
        - bearerAuth: []
      tags:
        - System Variable
      summary: 시스템 환경변수 생성
      description: 시스템 환경변수 신규 생성
      parameters:
        - in: path
          name: type
          description: 변수 구반값
          required: true
          schema:
            type: string
            example: POINT_CALC
        - in: path
          name: key
          description: 변수 명
          required: true
          schema:
            type: string
            example: CALC_1
      requestBody:
        description: 시스템 환경변수 데이터 값
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
                  example: '10'
                use:
                  type: boolean
                  example: true
                modifierEmail:
                  type: string
                  format: email
                  example: madam@example.com
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: SystemVariable
                example:
                  type: POINT_CALC
                  key: CALC_1
                  value: '10'
                  use: true
                  modifierName: Julius
                  createdAt: '2021-08-09T21:59:00.000Z'
                  modifiedAt: '2021-08-09T21:59:00.000Z'
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
    put:
      security:
        - bearerAuth: []
      tags:
        - System Variable
      summary: 시스템 환경변수 수정
      description: 시스템 환경변수 수정
      parameters:
        - in: path
          name: type
          description: 변수 구반값
          required: true
          schema:
            type: string
            example: POINT_CALC
        - in: path
          name: key
          description: 변수 명
          required: true
          schema:
            type: string
            example: CALC_1
      requestBody:
        description: 시스템 환경변수 데이터 값
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
                  example: '10'
                use:
                  type: boolean
                  example: true
                modifierEmail:
                  type: string
                  format: email
                  example: madam@example.com
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: SystemVariable
                example:
                  type: POINT_CALC
                  key: CALC_1
                  value: '10'
                  use: true
                  modifierName: Julius
                  createdAt: '2021-08-09T21:59:00.000Z'
                  modifiedAt: '2021-08-09T21:59:00.000Z'
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
    delete:
      security:
        - bearerAuth: []
      tags:
        - System Variable
      summary: 시스템 환경변수 삭제
      description: 시스템 환경변수 삭제
      parameters:
        - in: path
          name: type
          description: 변수 구반값
          required: true
          schema:
            type: string
            example: POINT_CALC
        - in: path
          name: key
          description: 변수 명
          required: true
          schema:
            type: string
            example: CALC_1
      responses:
        200:
          description: Success
        204:
          description: No Content
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
  /charm-plans:
    get:
      security:
        - bearerAuth: []
      tags:
        - Charm Plan
      summary: 포인트 플랜 목록 조회
      description: 포인트 플랜 목록 조회
      parameters:
        - in: query
          name: pageSize
          description: 조회 항목 개수
          required: true
          schema:
            type: integer
            format: int32
            example: 10
        - in: query
          name: pageNumber
          description: 조회 페이지 번호
          required: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  format: CharmPlan
                example:
                  - id: 1
                    name: Charm 10
                    description: 매력 포인트 +10
                    dollar: 10.00
                    charm: 10
                    order: 1
                    purchasedCount: 100000
                    createdAt: '2021-08-09T21:59:00.000Z'
                    modifiedAt: '2021-08-09T21:59:00.000Z'
                    modifierName: Julius
        204:
          description: No Content
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
    post:
      security:
        - bearerAuth: []
      tags:
        - Charm Plan
      summary: 포인트 플랜 생성
      description: 포인트 플랜 신규 생성
      requestBody:
        description: 포인트 플랜 데이터 값
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Charm 10
                description:
                  type: string
                  example: 매력 포인트 +10
                dollar:
                  type: integer
                  format: int32
                  example: 10.00
                charm:
                  type: integer
                  format: int32
                  example: 10
                order:
                  type: integer
                  format: int32
                  example: 1
                modifierEmail:
                  type: string
                  format: email
                  example: madam@example.com
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: CharmPlan
                example:
                  id: 1
                  name: Charm 10
                  description: 매력 포인트 +10
                  dollar: 10
                  charm: 10
                  modifierName: Julius
                  createdAt: '2021-08-09T21:59:00.000Z'
                  modifiedAt: '2021-08-09T21:59:00.000Z'
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
  /charm-plans/:id:
    put:
      security:
        - bearerAuth: []
      tags:
        - Charm Plan
      summary: 포인트 플랜 수정
      description: 포인트 플랜 수정
      parameters:
        - in: path
          name: id
          description: 포인트 플랜 고유 키
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        description: 포인트 플랜 데이터 값
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Charm 10
                description:
                  type: string
                  example: 매력 포인트 +10
                dollar:
                  type: integer
                  format: int32
                  example: 10.00
                charm:
                  type: integer
                  format: int32
                  example: 10
                order:
                  type: integer
                  format: int32
                  example: 1
                modifierEmail:
                  type: string
                  format: email
                  example: madam@example.com
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: CharmPlan
                example:
                  id: 1
                  name: Charm 10
                  description: 매력 포인트 +10
                  dollar: 10
                  charm: 10
                  modifierName: Julius
                  createdAt: '2021-08-09T21:59:00.000Z'
                  modifiedAt: '2021-08-09T21:59:00.000Z'
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
    delete:
      security:
        - bearerAuth: []
      tags:
        - Charm Plan
      summary: 포인트 플랜 삭제
      description: 포인트 플랜 삭제
      parameters:
        - in: path
          name: id
          description: 포인트 플랜 고유 키
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        200:
          description: Success
        204:
          description: No Content
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
  /help-desks:
    post:
      security:
        - bearerAuth: []
      tags:
        - Help Desk
      summary: 헬프데스크 생성/수정
      description: 헬프데스크 신규 생성 또는 수정
      requestBody:
        description: 헬프데스크 데이터 값
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                  enum:
                    - APP_BASE_KR
                    - APP_BASE_EN
                    - ACCOUNT_KR
                    - ACCOUNT_EN
                    - COUPLING_KR
                    - COUPLING_EN
                    - MEETING_KR
                    - MEETING_EN
                    - BEST_MADAM_KR
                    - BEST_MADAM_EN
                    - TEAM_KR
                    - TEAM_EN
                  example: APP_BASE_KR
                icon:
                  type: string
                  example: xi-close
                content:
                  type: string
                  example: |
                    # 헬프데스크
                      1. 이것은 헬프데스크입니다
                display:
                  type: boolean
                  example: true
                modifierEmail:
                  type: string
                  format: email
                  example: madam@example.com
      responses:
        200:
          description: Success
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
  /help-desks/:key:
    get:
      security:
        - bearerAuth: []
      tags:
        - Help Desk
      summary: 헬프데스크 조회
      description: 헬프데스크 글 조회
      parameters:
        - in: path
          name: key
          description: 헬프데스크 구분 키
          required: true
          schema:
            type: string
            enum:
              - APP_BASE_KR
              - APP_BASE_EN
              - ACCOUNT_KR
              - ACCOUNT_EN
              - COUPLING_KR
              - COUPLING_EN
              - MEETING_KR
              - MEETING_EN
              - BEST_MADAM_KR
              - BEST_MADAM_EN
              - TEAM_KR
              - TEAM_EN
            example: APP_BASE_KR
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: Guide
                example:
                  key: APP_BASE_KR
                  icon: xi-close
                  content: |
                    # 헬프데스크
                      1. 이것은 헬프데스크입니다
                  display: true
                  modifiedAt: '2021-08-09T21:59:00.000Z'
                  modifierName: Julius
        204:
          description: No Content
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
  /qna:
    get:
      security:
        - bearerAuth: []
      tags:
        - Q&A
      summary: 문의글 목록 조회
      description: 문의글 목록 조회 (삭제된 항목 제외)
      parameters:
        - in: query
          name: pageSize
          description: 조회 항목 개수
          required: true
          schema:
            type: integer
            format: int32
            example: 10
        - in: query
          name: pageNumber
          description: 조회 페이지 번호
          required: true
          schema:
            type: integer
            format: int32
            example: 1
        - in: query
          name: title
          description: 글 제목 (LIKE 검색)
          required: false
          schema:
            type: string
            example: 문의글
        - in: query
          name: type
          description: 글 유형
          required: false
          schema:
            type: string
            enum:
              - INQUIRY
              - REQUEST
              - ETC
            example: INQUIRY
        - in: query
          name: nickname
          description: 작성자 닉네임 (LIKE 검색)
          required: false
          schema:
            type: string
            example: Madam
        - in: query
          name: answered
          description: 답변여부
          required: false
          schema:
            type: boolean
            example: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  format: Inquiry
                example:
                  - id: 1
                    nickname: Madam
                    type: INQUIRY
                    title: 문의글
                    answered: true
                    answeredManagerName: Julius
                    createdAt: '2021-08-09T21:59:00.000Z'
                    answeredAt: '2021-08-09T21:59:00.000Z'
        204:
          description: No Content
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
  /qna/:id:
    get:
      security:
        - bearerAuth: []
      tags:
        - Q&A
      summary: 문의글 상세보기
      description: 문의글 상세보기
      parameters:
        - in: path
          name: id
          description: 문의글 고유 키
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: InquiryDetail
                example:
                  id: 1
                  nickname: Madam
                  type: INQUIRY
                  title: 문의글
                  content: |
                    # Madam앱이 좋은이유
                      - 최고니깐
                  answered: true
                  answeredManagerName: Julius
                  answer: |
                    # 감사합니다!
                  createdAt: '2021-08-09T21:59:00.000Z'
                  answeredAt: '2021-08-09T21:59:00.000Z'
                  answerModifiedAt: null
        204:
          description: No Content
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
    post:
      security:
        - bearerAuth: []
      tags:
        - Q&A
      summary: 문의글 답변 신규
      description: 문의글에 대한 답변 신규 생성(이메일 발신 필요)
      parameters:
        - in: path
          name: id
          description: 문의글 고유 키
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        description: 문의글 답변 데이터
        required: true
        content:
          application/json:
            schema:
              type: object
              format: InquiryAnswer
              example:
                id: 1
                content: |
                  # 감사합니다!
                modifierEmail: madam@example.com
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: InquiryDetail
                example:
                  id: 1
                  nickname: Madam
                  type: INQUIRY
                  title: 문의글
                  content: |
                    # Madam앱이 좋은이유
                      - 최고니깐
                  answered: true
                  answeredManagerName: Julius
                  answer: |
                    # 감사합니다!
                  createdAt: '2021-08-09T21:59:00.000Z'
                  answeredAt: '2021-08-09T21:59:00.000Z'
                  answerModifiedAt: null
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
    put:
      security:
        - bearerAuth: []
      tags:
        - Q&A
      summary: 문의글 답변 수정
      description: 기존에 답변을 단 문의글의 답변 수정(이메일 발신 필요)
      parameters:
        - in: path
          name: id
          description: 문의글 고유 키
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        description: 문의글 답변 데이터
        required: true
        content:
          application/json:
            schema:
              type: object
              format: InquiryAnswer
              example:
                id: 1
                content: |
                  # 감사합니다!
                modifierEmail: madam@example.com
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: InquiryDetail
                example:
                  id: 1
                  nickname: Madam
                  type: INQUIRY
                  title: 문의글
                  content: |
                    # Madam앱이 좋은이유
                      - 최고니깐
                  answered: true
                  answeredManagerName: Julius
                  answer: |
                    # 감사합니다!
                  createdAt: '2021-08-09T21:59:00.000Z'
                  answeredAt: '2021-08-09T21:59:00.000Z'
                  answerModifiedAt: null
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
    delete:
      security:
        - bearerAuth: []
      tags:
        - Q&A
      summary: 문의글 삭제
      description: 문의글 삭제
      parameters:
        - in: path
          name: id
          description: 문의글 고유 키
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        200:
          description: Success
        204:
          description: No Content
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
  /profile-extra:
    get:
      security:
        - bearerAuth: []
      tags:
        - Profile Extra Item
      summary: 유저 프로필 추가 관리 항목 목록
      description: 유저 프로필 추가 관리 항목 목록
      parameters:
        - in: query
          name: pageSize
          description: 조회 항목 개수
          required: true
          schema:
            type: integer
            format: int32
            example: 10
        - in: query
          name: pageNumber
          description: 조회 페이지 번호
          required: true
          schema:
            type: integer
            format: int32
            example: 1
        - in: query
          name: title
          description: 한글 또는 영문 명칭 (LIKE 검색)
          required: false
          schema:
            type: string
            example: MBTI
        - in: query
          name: type
          description: 추가항목 타입
          required: false
          schema:
            type: string
            enum:
              - TEXT
              - NUMBER
              - TEXT_AREA
              - SELECT
              - MULTI_SELECT
              - RADIO
            example: SELECT
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  format: ProfileExtraItem
                example:
                  - id: 1
                    titleKr: MBTI
                    titleEn: MBTI
                    type: SELECT
                    inputLength: null
                    modifiedAt: '2021-08-09T21:59:00.000Z'
                    modifierName: Julius
        204:
          description: No Content
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
    post:
      security:
        - bearerAuth: []
      tags:
        - Profile Extra Item
      summary: 유저 프로필 추가 관리 항목 신규 생성
      description: 유저 프로필 추가 관리 항목 신규 생성
      requestBody:
        description: 유저 프로필 추가 관리 항목 데이터
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titleKr:
                  type: string
                  example: MBTI
                titleEn:
                  type: string
                  example: MBTI
                type:
                  type: string
                  enum:
                    - TEXT
                    - NUMBER
                    - TEXT_AREA
                    - SELECT
                    - MULTI_SELECT
                    - RADIO
                  example: SELECT
                inputLength:
                  type: integer
                  format: int32
                  example: null
                modifierEmail:
                  type: string
                  format: email
                  example: madam@example.com
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: ProfileExtraItem
                example:
                  id: 1
                  titleKr: MBTI
                  titleEn: MBTI
                  type: SELECT
                  inputLength: null
                  modifiedAt: '2021-08-09T21:59:00.000Z'
                  modifierName: Julius
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
  /profile-extra/:id:
    put:
      security:
        - bearerAuth: []
      tags:
        - Profile Extra Item
      summary: 유저 프로필 추가 관리 항목 수정
      description: 유저 프로필 추가 관리 항목 수정 (SELECT 타입인 프로필 추가 항목을 위한 선택 요소에 영향)
      parameters:
        - in: path
          name: id
          description: 유저 프로필 추가 관리 항목 고유 키
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        description: 유저 프로필 추가 관리 항목 데이터
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titleKr:
                  type: string
                  example: MBTI
                titleEn:
                  type: string
                  example: MBTI
                type:
                  type: string
                  enum:
                    - TEXT
                    - NUMBER
                    - TEXT_AREA
                    - SELECT
                    - MULTI_SELECT
                    - RADIO
                  example: SELECT
                inputLength:
                  type: integer
                  format: int32
                  example: null
                modifierEmail:
                  type: string
                  format: email
                  example: madam@example.com
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: ProfileExtraItem
                example:
                  id: 1
                  titleKr: MBTI
                  titleEn: MBTI
                  type: SELECT
                  inputLength: null
                  modifiedAt: '2021-08-09T21:59:00.000Z'
                  modifierName: Julius
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
    delete:
      security:
        - bearerAuth: []
      tags:
        - Profile Extra Item
      summary: 유저 프로필 추가 관리 항목 삭제
      description: 유저 프로필 추가 관리 항목 삭제 (SELECT 타입인 프로필 추가 항목을 위한 선택 요소도 함께 삭제)
      parameters:
        - in: path
          name: id
          description: 유저 프로필 추가 관리 항목 고유 키
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        200:
          description: Success
        204:
          description: No Content
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
    get:
      security:
        - bearerAuth: []
      tags:
        - Profile Extra Item
      summary: 선택 요소 목록 조회
      description: SELECT 타입의 유저 프로필 추가 관리 항목에 대한 선택 요소 목록 조회
      parameters:
        - in: path
          name: id
          description: 유저 프로필 추가 관리 항목 고유 키
          required: true
          schema:
            type: integer
            format: int64
            example: 1
        - in: query
          name: pageSize
          description: 조회 항목 개수
          required: true
          schema:
            type: integer
            format: int32
            example: 10
        - in: query
          name: pageNumber
          description: 조회 페이지 번호
          required: true
          schema:
            type: integer
            format: int32
            example: 1
        - in: query
          name: key
          description: 선택요소 고유 키 (LIKE 검색)
          required: false
          schema:
            type: string
            example: ISTJ
        - in: query
          name: value
          description: 선택요소 값 (LIKE 검색)
          required: false
          schema:
            type: string
            example: ISTJ
        - in: query
          name: use
          description: 사용여부
          required: false
          schema:
            type: boolean
            example: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  format: ProfileSelectItem
                example:
                  - id: 1
                    key: ISTJ
                    value: ISTJ
                    use: true
                    modifiedAt: '2021-08-09T21:59:00.000Z'
                    modifierName: Julius
        204:
          description: No Content
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
    post:
      security:
        - bearerAuth: []
      tags:
        - Profile Extra Item
      summary: 선택 요소 신규 생성
      description: SELECT 타입의 유저 프로필 추가 관리 항목에 대한 선택 요소 신규 생성
      parameters:
        - in: path
          name: id
          description: 유저 프로필 추가 관리 항목 고유 키
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        description: 선택 요소 데이터
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                key: ISTJ
                value: ISTJ
                use: true
                modifierEmail: madam@example.com
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: ProfileSelectItem
                example:
                  id: 1
                  key: ISTJ
                  value: ISTJ
                  use: true
                  modifiedAt: '2021-08-09T21:59:00.000Z'
                  modifierName: Julius
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
  /profile-extra/:id/:key:
    put:
      security:
        - bearerAuth: []
      tags:
        - Profile Extra Item
      summary: 선택 요소 수정
      description: SELECT 타입의 유저 프로필 추가 관리 항목에 대한 선택 요소 수정
      parameters:
        - in: path
          name: id
          description: 유저 프로필 추가 관리 항목 고유 키
          required: true
          schema:
            type: integer
            format: int64
            example: 1
        - in: path
          name: key
          description: 선택요소 고유 키
          required: true
          schema:
            type: string
            example: ISTJ
      requestBody:
        description: 선택 요소 데이터
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                value: ISTJ
                use: true
                modifierEmail: madam@example.com
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: ProfileSelectItem
                example:
                  id: 1
                  key: ISTJ
                  value: ISTJ
                  use: true
                  modifiedAt: '2021-08-09T21:59:00.000Z'
                  modifierName: Julius
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
    delete:
      security:
        - bearerAuth: []
      tags:
        - Profile Extra Item
      summary: 선택 요소 삭제
      description: SELECT 타입의 유저 프로필 추가 관리 항목에 대한 선택 요소 삭제
      parameters:
        - in: path
          name: id
          description: 유저 프로필 추가 관리 항목 고유 키
          required: true
          schema:
            type: integer
            format: int64
            example: 1
        - in: path
          name: key
          description: 선택요소 고유 키
          required: true
          schema:
            type: string
            example: ISTJ
      responses:
        200:
          description: Success
        204:
          description: No Content
        400:
          description: Invalid Request Param
        403:
          description: No Authority
        500:
          description: Server Error
